version: '3'

services:
  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   ports:
  #     - '6379:6379'
  # mongodb:
  #   image: mongo:4.4.6
  #   volumes:
  #     - ./mongo:/data/db
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=app_user
  #     - MONGO_INITDB_ROOT_PASSWORD=app_password
  #     - MONGO_INITDB_DATABASE=admin

  # pgadmin
  pgadmin:
    image: dpage/pgadmin4:5.6
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nest.com
      - PGADMIN_DEFAULT_PASSWORD=nest
  postgres:
    image: postgres:13.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
